aliases:
  - &restore-cache
    keys:
      - dependencies-{{ checksum "package.json" }}
      - dependencies-

  - &restore-example-cache
    keys:
      - dependencies-example-{{ checksum "example/package.json" }}
      - dependencies-example

  - &restore-website-cache
    keys:
      - dependencies-website-{{ checksum "website/package.json" }}
      - dependencies-website

  - &save-cache
    key: dependencies-{{ checksum "package.json" }}
    paths: node_modules

  - &save-example-cache
    key: dependencies-example-{{ checksum "example/package.json" }}
    paths: example/node_modules

  - &save-website-cache
    key: dependencies-website-{{ checksum "website/package.json" }}
    paths: website/node_modules

  - &filter-only-master
    branches:
      only: master

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

  - &filter-tag
    tags:
      only: /v\d+\.\d+\.\d+.*/
    # branches:
    #   ignore: /.*/

defaults: &defaults
  working_directory: ~/react-native-ios-kit
  docker:
    - image: circleci/node:10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-native-ios-kit
      - restore-cache: *restore-cache
      - restore-cache: *restore-example-cache
      - restore-cache: *restore-website-cache
      - run: |
          yarn install --ignore-scripts --frozen-lockfile
          yarn install --ignore-scripts --frozen-lockfile --cwd ./website
          yarn install --ignore-scripts --frozen-lockfile --cwd ./example
      - save-cache: *save-cache
      - save-cache: *save-example-cache
      - save-cache: *save-website-cache
      - persist_to_workspace:
          root: .
          paths: .

  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-ios-kit
      - run: yarn run lint
      - run: yarn flow

  deploy-website:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-native-ios-kit
      - add_ssh_keys:
          fingerprints:
            - '11:06:5b:a1:d0:c5:8a:49:cd:8d:05:7f:d9:7d:15:3d'
      - run: |
          echo "Deploying website..."
          git config --global user.name "$CIRCLE_USERNAME"
          git config --global user.email "oss@callstack.com"
          cd website && GIT_USER="$CIRCLE_USERNAME" USE_SSH=true yarn run deploy

  publish-expo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-ios-kit
      - run: |
          cd example
          yarn exp login -u "$EXP_USERNAME" -p "$EXP_PASSWORD"
          yarn exp publish --non-interactive

workflows:
  version: 2

  build-and-test:
    jobs:
      - build:
          filters:  # required since `deploy-website` amd `publish-expo` has tag filters AND requires `build`
            tags:
              only: /.*/
      - tests:
          requires:
            - build
          filters: *filter-ignore-gh-pages
      - deploy-website:
          requires:
            - build
          filters: *filter-tag
      - publish-expo:
          requires:
            - build
          filters: *filter-tag
