aliases:
  - &restore-cache
    keys:
      - dependencies-{{ checksum "package.json" }}
      # Fallback in case checksum fails
      - dependencies-

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ checksum "package.json" }}


defaults: &defaults
  working-directory: ~/react-native-ios-kit
  docker: 
    - image: circleci/node:6

version: 2
jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn install
      - save-cache: *save-cache
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn test -- --coverage -i
      - store_artifacts:
          path: coverage
  deploy-website:
    <<: *defaults
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn install
      - save-cache: *save-cache
      - add_ssh_keys:
          fingerprints:
           - "83:32:d9:cc:14:f0:ec:9a:ea:c7:4d:0b:31:74:53:06"
      - run:
          name: Deploy Website
          commands: 
            - echo "Deploying website..."          
            - cd website && GIT_USER="$COMMIT_AUTHOR_NAME" USE_SSH=true yarn run publish-gh-pages
  
workflows:
  version: 2

  website: 
    jobs:
      - tests:
          filters: 
            branches:
              ignore: gh-pages
      - deploy-website:
          requires:
            - tests
