name: "Pull Request Labeler"
on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened, ready_for_review, synchronize]

jobs:
  triage:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    name: Label issues and pull requests
    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: labeler
        uses: IvanFon/super-labeler-action@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
